// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-training-sessions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-training-sessions.ts
var list_training_sessions_default = defineTool({
  name: "list_training_sessions",
  title: "List training sessions",
  description: "List upcoming or past Football Basics training sessions with date, time, location and title.",
  inputSchema: {
    upcoming_only: z.boolean().optional().describe("Only return sessions from today onwards. Defaults to true."),
    limit: z.number().int().optional().describe("Maximum number of sessions to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ upcoming_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("training_sessions").select("id, title, description, session_date, session_time, location, max_participants, is_completed").order("session_date", { ascending: true }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (upcoming_only !== false) {
      query = query.gte("session_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/sign-up-for-training.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var sign_up_for_training_default = defineTool2({
  name: "sign_up_for_training",
  title: "Sign up for a training session",
  description: "Sign the current player up for a Football Basics training session by session id.",
  inputSchema: {
    session_id: z2.string().describe("The id of the training session to join.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing } = await supabase.from("session_signups").select("id").eq("session_id", session_id).eq("user_id", userId).maybeSingle();
    if (existing) {
      return { content: [{ type: "text", text: "Already signed up for this session." }] };
    }
    const { data, error } = await supabase.from("session_signups").insert({ session_id, user_id: userId }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Signed up for session ${session_id}.` }],
      structuredContent: { signup: data }
    };
  }
});

// src/lib/mcp/tools/get-my-stats.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_stats_default = defineTool3({
  name: "get_my_stats",
  title: "Get my player stats",
  description: "Get the signed-in player's Football Basics profile and stats (sessions attended, crossbars hit, speeds).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("username, first_name, sessions_attended, crossbars_hit, running_speed, shooting_speed, session_quota").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this account." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/submit-training-suggestion.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_training_suggestion_default = defineTool4({
  name: "submit_training_suggestion",
  title: "Submit a training focus suggestion",
  description: "Submit a suggestion for what a Football Basics training should focus on, optionally tied to a session.",
  inputSchema: {
    suggestion: z3.string().describe("The training focus suggestion text."),
    session_id: z3.string().optional().describe("Optional id of the session the suggestion relates to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ suggestion, session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const text = suggestion.trim();
    if (!text) return { content: [{ type: "text", text: "Suggestion cannot be empty." }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("training_focus_suggestions").insert({ user_id: ctx.getUserId(), suggestion: text, session_id: session_id ?? null }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Suggestion submitted." }],
      structuredContent: { suggestion: data }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool5({
  name: "get_leaderboard",
  title: "Get the player leaderboard",
  description: "Get the Football Basics player ranking by sessions attended or crossbars hit.",
  inputSchema: {
    sort_by: z4.enum(["sessions_attended", "crossbars_hit"]).optional().describe("Ranking metric, defaults to sessions_attended."),
    limit: z4.number().int().optional().describe("Number of players to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sort_by, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const column = sort_by ?? "sessions_attended";
    const { data, error } = await supabase.from("profiles").select("username, first_name, sessions_attended, crossbars_hit").order(column, { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leaderboard: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wemmmtbyqclcxtlxqmen";
var mcp_default = defineMcp({
  name: "football-basics",
  title: "Football Basics",
  version: "0.1.0",
  instructions: "Tools for the Football Basics training app. List training sessions, sign the signed-in player up for a session, read their stats, view the leaderboard, and submit training focus suggestions. All tools act as the authenticated player.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_training_sessions_default,
    sign_up_for_training_default,
    get_my_stats_default,
    get_leaderboard_default,
    submit_training_suggestion_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
